#!/bin/bash

db_user=owncloud
db_name=owncloud
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting owncloud domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/owncloud
sudo rm -rf /home/yunohost.app/owncloud
sudo rm -f /etc/nginx/conf.d/$domain.d/owncloud.conf
sudo rm -f /etc/php5/fpm/pool.d/owncloud.conf
for i in $(ls /home)
do
    if [[ ! $i == yunohost.* ]];
    then
        sudo setfacl -x g:owncloud:rwx > /dev/null 2>&1
    fi
done
sudo killall php5-fpm
sudo service php5-fpm start
sudo userdel owncloud > /dev/null 2>&1
sudo service nginx reload
